---

- hosts: all
  sudo: yes

  vars:
    virtualenv_path: "/tmp/venv"
    django_project_name: "mytestingsite"

  tasks:
    - name: install epel
      yum: "name=http://mirror.steadfast.net/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present"

    - yum: "name={{ item }} state=present"
      with_items:
        - python-pip
        - httpd
        - mod_wsgi

    - name: install virtual env
      pip: name=virtualenv state=present

    - name: create virtualenv
      command: "virtualenv {{ virtualenv_path }}"

    - name: install requirements
      pip: "requirements=/vagrant/requirements.txt virtualenv={{ virtualenv_path }}"

    - name: Create django project directory
      file: "path=/tmp/{{ django_project_name }} state=directory"

    - name: Create django project
      shell: "source {{ virtualenv_path }}/bin/activate && django-admin startproject {{ django_project_name }} /tmp/{{ django_project_name }} creates=/tmp/{{ django_project_name }}/{{ django_project_name }}"

    - name: Copy settings.py
      copy: "src=files/settings.py dest=/tmp/{{ django_project_name }}/{{ django_project_name }}/settings.py"

    - name: Link app from /vagrant/kombucha_manager to vagrant django project
      file: "src=/vagrant/mysite/kombucha_manager dest=/tmp/{{ django_project_name }}/kombucha_manager state=link"

    - name: Perform Django Database Migrations
      django_manage:
      args:
        virtualenv: "{{ virtualenv_path }}"
        command: migrate
        app_path: "/tmp/{{ django_project_name }}"

    - name: copy WSGI http.conf
      template: src=templates/wsgi.conf.j2 dest=/etc/httpd/conf.d/wsgi.conf
      notify:
      - restart httpd

    - name: ensure httpd is started
      service: name=httpd state=started

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
