---

- hosts: all
  sudo: yes

  tasks:
    - name: install epel
      yum: "name=http://mirror.steadfast.net/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present"

    - yum: "name={{ item }} state=present"
      with_items:
        - python-pip
        - python-devel
        - postgresql
        - postgresql-devel
        - postgresql-contrib
        - postgresql-server
        - gcc
        - make

    - name: install requirements
      pip: "requirements=/vagrant/requirements.txt"

    - command: "/bin/postgresql-setup initdb"
      ignore_errors: true

    - service: name=postgresql state=started enabled=true

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: false
  vars:
    db_name: mysite
    db_user: bucha
    db_pass: br00klyn

  tasks:
    - name: create database
      postgresql_db:
      args:
        name: "{{ db_name }}"
    - name: create database user
      postgresql_user:
      args:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "ALL"

- hosts: all
  sudo: yes
  gather_facts: false
  vars:
    db_name: mysite
    db_user: bucha
    db_pass: br00klyn
    database_url: 'postgres://{{db_user}}:{{db_pass}}@localhost/{{db_name}}'
  tasks:
    - name: Perform Django Database Migrations
      command: "DATABASE_URL='{{ database_url }}' /usr/bin/python /vagrant/manage.py migrate"

    - name: start gnuicorn
      command: "DATABASE_URL='{{ database_url }}' gunicorn mysite.wsgi --log-file /tmp/gunicorn.log -D"
