---

- hosts: all
  sudo: yes

  tasks:
    - name: install epel
      yum: "name=http://mirror.steadfast.net/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present"

    - yum: "name={{ item }} state=present"
      with_items:
        - python-pip
        - python-devel
        - postgresql
        - postgresql-devel
        - postgresql-contrib
        - postgresql-server
        - gcc
        - make

    - name: disable firewall
      service: name=firewalld state=stopped enabled=false

    - name: install requirements
      pip: "requirements=/vagrant/requirements.txt"

    - command: "/bin/postgresql-setup initdb creates=/var/lib/pgsql/data/pg_hba.conf"
      ignore_errors: true

    - replace:
      args:
        dest: /var/lib/pgsql/data/pg_hba.conf
        regexp: 'host[ \t]* all[ \t]* all[ \t]* 127.0.0.1/32[ \t]*ident'
        replace: 'host   all  all    127.0.0.1/32    trust'

    - service: name=postgresql state=started enabled=true

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: false
  vars:
    db_name: mysite
    db_user: bucha
    db_pass: br00klyn

  tasks:
    - name: create database
      postgresql_db:
      args:
        name: "{{ db_name }}"
    - name: create database user
      postgresql_user:
      args:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "ALL"

- hosts: all
  sudo: yes
  gather_facts: false
  vars:
    db_name: mysite
    db_user: bucha
    db_pass: br00klyn
    database_url: 'postgres://{{db_user}}:{{db_pass}}@127.0.0.1/{{db_name}}'
  tasks:
    - name: kill gunicorn
      shell: "pkill -9 gunicorn"
      register: kill_gunicorn
      failed_when: "kill_gunicorn.rc > 1"

    - name: Perform Django Database Migrations for auth
      shell: "DATABASE_URL='{{ database_url }}' /usr/bin/python /vagrant/manage.py migrate auth"

    - name: Perform Django Database Migrations
      shell: "DATABASE_URL='{{ database_url }}' /usr/bin/python /vagrant/manage.py migrate"

#    - name: Create admin user
#      shell: "DATABASE_URL='{{ database_url }}' /usr/bin/python /vagrant/manage.py loaddata /vagrant/provision/files/data.json"

    - name: start gnuicorn
      shell: "DATABASE_URL='{{ database_url }}' gunicorn mysite.wsgi --log-file /tmp/gunicorn.log -D --pythonpath=/vagrant/ --bind 0.0.0.0:8000"
