db:
  image: postgres
web:
  build: .
  environment:
    DJANGO_DEBUG: 'true'
    DATABASE_URL: 'postgres://postgres:postgres@db/postgres'
  command: 'bash provision/files/docker-entrypoints.sh'
  volumes:
    - .:/kombucha-manager-site
  ports:
    - "5000:5000"
  links:
    - db
